### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DDZiroWan** [spoorn/SpoornWeaponAttributes#2]
These are suggestions regarding how weapon effects could change depending on how high attributes are, instead of only damage dealt changing..

- Fire duration could be proportional to the attribute.
- Poison effect could be differentiated from fire by dealing more damage over more time instead of being almost the same dps as fire. Could be done by reducing the level of poison to 1 and making the poison duration 6 seconds for every point of poison.
- Cold damage could use the new freezing mechanic instead of the slowness effect. Every attack would add (34+attribute) TicksFreezing to the target (10 consecutive hits with a cold damage attribute of 1 would freeze the target in 10 hits). The cap for TicksFreezing should be raised to a higher number tho (2400 seems reasonable, it's roughly 1 minute of freezing with freezing damage. Remember TicksFreezing tick down by 2 every game tick)
- The lightning strike chance could be proportional to the attribute. Chance could be (0.05*attribute)
- The explosive attribute instead of boolean could be numerical like the others and explosion power could be proportional to the attribute. I would suggest explosionPower=(3x+16)/19}

Also a config option to disable certain attributes from doing extra damage would be appreciate :)

**Comment by spoorn** [comment]
Thanks for suggestions

New update (also backported to 1.16): https://github.com/spoorn/SpoornWeaponAttributes/commit/7f19a4220b1b527901af7d783308db04c9393789

Added expression type strings for various durations, and freeze mechanic.  

Didn't change lightning strike or explosive though as those 2 effects are more impactful/unique than the others and I want them to be a flat enhancement rather than scaling to prevent over/underpowered weapons.

You should be able to disable extra damage by setting maxDamage to 0

**Comment by spoorn** [comment]
If you have more ideas feel free to suggest, or even add them yourselves via a pull request

**Comment by DDZiroWan** [comment]
👍 👍
